default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Mathieu19
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production